apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-kustomize
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  sources:
    - repoURL: https://github.com/chengfang/image-updater-examples.git
      targetRevision: main
      path: multi-source-kustomize/source1
    - repoURL: https://github.com/chengfang/image-updater-examples.git
      targetRevision: main
      path: multi-source-kustomize/source2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
