apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: kustomize-helmvalues
  namespace: argocd-e2e
spec:
  namespace: argocd-e2e
  applicationRefs:
    - namePattern: "kustomize-helmvalues"
      images:
        - alias: "nginx"
          imageName: "docker.io/bitnamilegacy/nginx:1.27.x"
          commonUpdateSettings:
            updateStrategy: "semver"
            forceUpdate: false
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
  writeBackConfig:
    method: "git:secret:argocd-e2e/git-creds"
    gitConfig:
      repository: "https://github.com/chengfang/image-updater-examples.git"
      branch: "main"
      writeBackTarget: "helmvalues:/kustomize-helmvalues/source2/values.yaml"
