apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "18.2.3"
      chart: nginx
      helm:
        valueFiles:
          - $values/multi-source-helm/source2/values.yaml
    - repoURL: https://github.com/chengfang/image-updater-examples.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
